#!/bin/sh

# Create key
#-----------

if [ ! -e /var/clearos/suva/key_generated ]; then
    logger -p local6.notice -t installer "app-suva-core - generating hostkey"
    /usr/bin/mkhost.sh /etc/suvad.conf
    touch /var/clearos/suva/key_generated
fi
